version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8081:8081
    environment:
      - SERVER_ENV=local
      - EVENT_PAYLOAD_SECRET_KEY=TEST_EVENT_PAYLOAD_SECRET_KEY___
      - BASIC_AUTHORIZATION_VALUE=TEST_BASIC_AUTHORIZATION_VALUE
      - BUZZAD_URL=https://ad-dev.buzzvil.com
      - REWARDSVC_URL=rewardsvc-dev.rewardsvc:9000
      - BUZZSCREEN_API_URL=https://screen-dev.buzzvil.com
      - AMQP_URL=amqp://nxnffuhv:vakD-wYwV4e9ycNDZWf9Bd60dFifbQ5m@cougar.rmq.cloudamqp.com/nxnffuhv
    volumes:
      - ".:/go/src/github.com/Buzzvil/buzzscreen-api:delegated"
    command: go run -v /go/src/github.com/Buzzvil/buzzscreen-api/main.go
